### ISSUE TITLE
Error when running an itinerary request

### ISSUE THREAD

**Issue by abrahampersil** [CanalTP/demo.navitia.io#10]
When requesting trips using demo.navitia.io, I got a various number of these errors:

Notice: Undefined property: stdClass::$comment in /srv/www/demo.navitia.io/releases/demo.navitia.io-0.13.0/classes/Model/Entity/Transport/StopArea.php on line 84

Could you please fix it?

Thanks :)

**Comment by is06** [comment]
Thank you for your feedback, we are working on this issue to solve it soon.
