### ISSUE TITLE
Fatal error and impossibility to get timetables

### ISSUE THREAD

**Issue by kalon33** [CanalTP/demo.navitia.io#11]
When trying to get timetables, I got this fatal error after choosing an agency:

Fatal error: Call to private method Nv2\Model\Entity\Transport\Line::getList() from context 'Nv2\Controller\Schedule\ScheduleSelectLineController' in /srv/www/demo.navitia.io/releases/demo.navitia.io-0.13.0/classes/Controller/Schedule/ScheduleSelectLineController.php on line 32

Of course, it's impossible to choose any line after that (no dropdown menu)

**Comment by is06** [comment]
Thank you for your feedback, we are working on this issue to solve it soon.

**Comment by kalon33** [comment]
Thanks :)

Now when choosing "timetables" and "transilien", and then choosing a point on the map, I'm getting this error:


Fatal error: Class 'Nv2\Model\NavitiaApi\Schedule\DepartureBoards' not found in /srv/www/demo.navitia.io/releases/demo.navitia.io-0.13.0/classes/Controller/Schedule/ScheduleProximityBoardController.php on line 55


Thanks for your help.

**Comment by kalon33** [comment]
@is06 , does that also fix the problem I described in my last comment?

Thanks :)
